[mypbuiler] Add qemu-debootstrap for foreign pbuilder

diff --git a/usr/bin/mypbuilder b/usr/bin/mypbuilder
--- a/usr/bin/mypbuilder
+++ b/usr/bin/mypbuilder
@@ -4,6 +4,8 @@
 
 BASEDIR="$HOME/pbuilder"
 PBUILDER_TMP=/tmp/pbuilder
+DEBOOTSTRAP=debootstrap
+FOREIGN_DEBOOTSTRAP=qemu-debootstrap
 
 DIST=$1
 DEB_TARGET_ARCH=$2
@@ -24,6 +26,15 @@ else
     DEB_HOST_ARCH=`dpkg-architecture -qDEB_HOST_ARCH`
     DEB_HOST_ARCH_BITS=`dpkg-architecture -qDEB_HOST_ARCH_BITS`
     DEB_TARGET_ARCH_BITS=`dpkg-architecture -a$DEB_TARGET_ARCH -qDEB_HOST_ARCH_BITS`
+fi
+
+if [ "$DEB_TARGET_ARCH" != "$DEB_HOST_ARCH" ]; then
+    if ! `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin which $FOREIGN_DEBOOTSTRAP > /dev/null`; then
+        printf "E: $FOREIGN_DEBOOTSTRAP required when host and target architectures do not match.\n"
+        exit 1
+    else
+        DEBOOTSTRAP=$FOREIGN_DEBOOTSTRAP
+    fi
 fi
 
 unset $ARG
@@ -121,6 +132,7 @@ PBUILDER_CMD="sudo DEB_BUILD_PARALLEL=1 DEB_BUILD_OPTIONS=parallel=${NJOBS} $ARG
 COMMON_ARGS="--override-config \
     --autocleanaptcache \
     --compressprog pigz \
+    --debootstrap $DEBOOTSTRAP \
     --architecture $DEB_TARGET_ARCH \
     --distribution $DISTRO \
     --configfile $BASEDIR/etc/$DIST-$DEB_TARGET_ARCH-pbuilderrc \
