Improve error messages

diff --git a/usr/bin/mypbuilder b/usr/bin/mypbuilder
--- a/usr/bin/mypbuilder
+++ b/usr/bin/mypbuilder
@@ -12,13 +12,13 @@ DSCFILE=$4
 
 for i in pbuilder pigz dpkg-architecture; do
     if ! `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin which $i > /dev/null`; then
-        printf "E: $i not found in PATH.\n" 1>&2
+        printf "E: Required command \"$i\" not found.\n" 1>&2
         exit 1
     fi
 done
 
 if ! `dpkg-architecture -a$DEB_TARGET_ARCH >/dev/null 2>&1`; then
-    printf "E: $DEB_TARGET_ARCH is not a valid architecture.\n" 1>&2
+    printf "E: \"$DEB_TARGET_ARCH\" is not a valid architecture.\n" 1>&2
     exit 1
 else
     DEB_HOST_ARCH=`dpkg-architecture -qDEB_HOST_ARCH`
